# Generated by Django 3.2.12 on 2022-04-23 18:51

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
