# Generated by Django 3.2.12 on 2022-04-23 13:13

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
