# Generated by Django 3.2.12 on 2022-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 'Любовь'), (4, 'Обожание'), (3, 'Нейтрально'), (2, 'Неприязнь'), (1, 'Ненависть')], null=True, verbose_name='Оценка'),
        ),
    ]
