# Generated by Django 3.2.12 on 2022-04-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Любовь'), (4, 'Обожание'), (3, 'Нейтрально'), (2, 'Неприязнь'), (1, 'Ненависть'), (0, 'Оценка отсутствует')], default=0, verbose_name='Оценка'),
        ),
    ]
