# Generated by Django 4.0.3 on 2022-03-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'verbose_name': 'Полка', 'verbose_name_plural': 'Полки'},
        ),
    ]
