# Generated by Django 3.2.12 on 2022-03-25 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_item_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ratings',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='catalog.category', verbose_name='Категория'),
        ),
    ]
